### ISSUE TITLE
Query parameter decoding not correctly handling plus signs

### ISSUE THREAD

**Issue by gavbaa** [xapijs/xapi#175]
How I tripped on this: noticed that my actor names were coming into the LRS as {"name": "Mary+Sue"}, not {"name": "Mary Sue"} as I would have expected. I verified all other forms of decoding on either end of the situation, it's a specific problem with the native JS decodeURIComponent, and all modern browsers provide URLSearchParams instead to get more accurate behavior.  I propose PR #174 to address this.

**Comment by CookieCookson** [comment]
Hi @gavbaa, thank you for raising the issue and providing a suitable fix. (Plus tests are always a bonus!)

It was originally implemented this way to cater for IE11 support, but I am very much in the mindset now of requiring projects to polyfill instead of the library catering for old tech.

I'll give this a review and get it released soon 😊

**Comment by CookieCookson** [comment]
Fixed in #174, will be released shortly. Thanks again for the contribution!

**Comment by CookieCookson** [comment]
Released in 1.2.1 🎉
